import * as vscode from 'vscode';

interface CharacterDisplay extends vscode.QuickPickItem {
	printable: boolean
}

export function activate(context: vscode.ExtensionContext) {
	let items: CharacterDisplay[] = [
		{ label: "NUL", description: "0 (0x00)", detail: "null", printable: false },
		{ label: "SOH", description: "1 (0x01)", detail: "start of headline", printable: false },
		{ label: "STX", description: "2 (0x02)", detail: "start of text", printable: false },
		{ label: "ETX", description: "3 (0x03)", detail: "end of text", printable: false },
		{ label: "EOT", description: "4 (0x04)", detail: "end of transmission", printable: false },
		{ label: "ENQ", description: "5 (0x05)", detail: "enquiry", printable: false },
		{ label: "ACK", description: "6 (0x06)", detail: "acknowledge", printable: false },
		{ label: "BEL", description: "7 (0x07)", detail: "bell", printable: false },
		{ label: "BS", description: "8 (0x08)", detail: "backspace", printable: false },
		{ label: "HT", description: "9 (0x09)", detail: "horizontal tab", printable: false },
		{ label: "LF", description: "10 (0x0A)", detail: "NL line feed, new line", printable: false },
		{ label: "VT", description: "11 (0x0B)", detail: "vertical tab", printable: false },
		{ label: "FF", description: "12 (0x0C)", detail: "NP form feed, new page", printable: false },
		{ label: "CR", description: "13 (0x0D)", detail: "carriage return", printable: false },
		{ label: "SO", description: "14 (0x0E)", detail: "shift out", printable: false },
		{ label: "SI", description: "15 (0x0F)", detail: "shift in", printable: false },
		{ label: "DLE", description: "16 (0x10)", detail: "data link escape", printable: false },
		{ label: "DC1", description: "17 (0x11)", detail: "device control 1", printable: false },
		{ label: "DC2", description: "18 (0x12)", detail: "device control 2", printable: false },
		{ label: "DC3", description: "19 (0x13)", detail: "device control 3", printable: false },
		{ label: "DC4", description: "20 (0x14)", detail: "device control 4", printable: false },
		{ label: "NAK", description: "21 (0x15)", detail: "negative acknowledge", printable: false },
		{ label: "SYN", description: "22 (0x16)", detail: "synchronous idle", printable: false },
		{ label: "ETB", description: "23 (0x17)", detail: "end of trans. block", printable: false },
		{ label: "CAN", description: "24 (0x18)", detail: "cancel", printable: false },
		{ label: "EM", description: "25 (0x19)", detail: "end of medium", printable: false },
		{ label: "SUB", description: "26 (0x1A)", detail: "substitute", printable: false },
		{ label: "ESC", description: "27 (0x1B)", detail: "escape", printable: false },
		{ label: "FS", description: "28 (0x1C)", detail: "file separator", printable: false },
		{ label: "GS", description: "29 (0x1D)", detail: "group separator", printable: false },
		{ label: "RS", description: "30 (0x1E)", detail: "record separator", printable: false },
		{ label: "US", description: "31 (0x1F)", detail: "unit separator", printable: false },
		{ label: " ", description: "32 (0x20)", detail: "space", printable: true },
		{ label: "!", description: "33 (0x21)", printable: true },
		{ label: "\"", description: "34 (0x22)", printable: true },
		{ label: "#", description: "35 (0x23)", printable: true },
		{ label: "$", description: "36 (0x24)", printable: true },
		{ label: "%", description: "37 (0x25)", printable: true },
		{ label: "&", description: "38 (0x26)", printable: true },
		{ label: "'", description: "39 (0x27)", printable: true },
		{ label: "(", description: "40 (0x28)", printable: true },
		{ label: ")", description: "41 (0x29)", printable: true },
		{ label: "*", description: "42 (0x2A)", printable: true },
		{ label: "+", description: "43 (0x2B)", printable: true },
		{ label: ",", description: "44 (0x2C)", printable: true },
		{ label: "-", description: "45 (0x2D)", printable: true },
		{ label: ".", description: "46 (0x2E)", printable: true },
		{ label: "/", description: "47 (0x2F)", printable: true },
		{ label: "0", description: "48 (0x30)", printable: true },
		{ label: "1", description: "49 (0x31)", printable: true },
		{ label: "2", description: "50 (0x32)", printable: true },
		{ label: "3", description: "51 (0x33)", printable: true },
		{ label: "4", description: "52 (0x34)", printable: true },
		{ label: "5", description: "53 (0x35)", printable: true },
		{ label: "6", description: "54 (0x36)", printable: true },
		{ label: "7", description: "55 (0x37)", printable: true },
		{ label: "8", description: "56 (0x38)", printable: true },
		{ label: "9", description: "57 (0x39)", printable: true },
		{ label: ":", description: "58 (0x3A)", printable: true },
		{ label: ";", description: "59 (0x3B)", printable: true },
		{ label: "<", description: "60 (0x3C)", printable: true },
		{ label: "=", description: "61 (0x3D)", printable: true },
		{ label: ">", description: "62 (0x3E)", printable: true },
		{ label: "?", description: "63 (0x3F)", printable: true },
		{ label: "@", description: "64 (0x40)", printable: true },
		{ label: "A", description: "65 (0x41)", printable: true },
		{ label: "B", description: "66 (0x42)", printable: true },
		{ label: "C", description: "67 (0x43)", printable: true },
		{ label: "D", description: "68 (0x44)", printable: true },
		{ label: "E", description: "69 (0x45)", printable: true },
		{ label: "F", description: "70 (0x46)", printable: true },
		{ label: "G", description: "71 (0x47)", printable: true },
		{ label: "H", description: "72 (0x48)", printable: true },
		{ label: "I", description: "73 (0x49)", printable: true },
		{ label: "J", description: "74 (0x4A)", printable: true },
		{ label: "K", description: "75 (0x4B)", printable: true },
		{ label: "L", description: "76 (0x4C)", printable: true },
		{ label: "M", description: "77 (0x4D)", printable: true },
		{ label: "N", description: "78 (0x4E)", printable: true },
		{ label: "O", description: "79 (0x4F)", printable: true },
		{ label: "P", description: "80 (0x50)", printable: true },
		{ label: "Q", description: "81 (0x51)", printable: true },
		{ label: "R", description: "82 (0x52)", printable: true },
		{ label: "S", description: "83 (0x53)", printable: true },
		{ label: "T", description: "84 (0x54)", printable: true },
		{ label: "U", description: "85 (0x55)", printable: true },
		{ label: "V", description: "86 (0x56)", printable: true },
		{ label: "W", description: "87 (0x57)", printable: true },
		{ label: "X", description: "88 (0x58)", printable: true },
		{ label: "Y", description: "89 (0x59)", printable: true },
		{ label: "Z", description: "90 (0x5A)", printable: true },
		{ label: "[", description: "91 (0x5B)", printable: true },
		{ label: "\\", description: "92 (0x5C)", printable: true },
		{ label: "]", description: "93 (0x5D)", printable: true },
		{ label: "^", description: "94 (0x5E)", printable: true },
		{ label: "_", description: "95 (0x5F)", printable: true },
		{ label: "`", description: "96 (0x60)", printable: true },
		{ label: "a", description: "97 (0x61)", printable: true },
		{ label: "b", description: "98 (0x62)", printable: true },
		{ label: "c", description: "99 (0x63)", printable: true },
		{ label: "d", description: "100 (0x64)", printable: true },
		{ label: "e", description: "101 (0x65)", printable: true },
		{ label: "f", description: "102 (0x66)", printable: true },
		{ label: "g", description: "103 (0x67)", printable: true },
		{ label: "h", description: "104 (0x68)", printable: true },
		{ label: "i", description: "105 (0x69)", printable: true },
		{ label: "j", description: "106 (0x6A)", printable: true },
		{ label: "k", description: "107 (0x6B)", printable: true },
		{ label: "l", description: "108 (0x6C)", printable: true },
		{ label: "m", description: "109 (0x6D)", printable: true },
		{ label: "n", description: "110 (0x6E)", printable: true },
		{ label: "o", description: "111 (0x6F)", printable: true },
		{ label: "p", description: "112 (0x70)", printable: true },
		{ label: "q", description: "113 (0x71)", printable: true },
		{ label: "r", description: "114 (0x72)", printable: true },
		{ label: "s", description: "115 (0x73)", printable: true },
		{ label: "t", description: "116 (0x74)", printable: true },
		{ label: "u", description: "117 (0x75)", printable: true },
		{ label: "v", description: "118 (0x76)", printable: true },
		{ label: "w", description: "119 (0x77)", printable: true },
		{ label: "x", description: "120 (0x78)", printable: true },
		{ label: "y", description: "121 (0x79)", printable: true },
		{ label: "z", description: "122 (0x7A)", printable: true },
		{ label: "{", description: "123 (0x7B)", printable: true },
		{ label: "|", description: "124 (0x7C)", printable: true },
		{ label: "}", description: "125 (0x7D)", printable: true },
		{ label: "~", description: "126 (0x7E)", printable: true },
		{ label: "DEL", description: "127 (0x7F)", detail: "delete", printable: false }];
	let allDisposable = vscode.commands.registerCommand('extension.allChars', () => {
		vscode.window.showQuickPick(items);
	});

	let printableItems: vscode.QuickPickItem[] = items.filter(item => item.printable);
	let printableDisposable = vscode.commands.registerCommand('extension.printableChars', () => {
		vscode.window.showQuickPick(printableItems);
	});

	context.subscriptions.push(allDisposable);
	context.subscriptions.push(printableDisposable);
}

export function deactivate() { }
